### PR TITLE
Fix horizontal scrollbar

### PR DESCRIPTION
**Pull request by ryantmer**
The `width` here was causing the search bar to be wider than the dropdown-content container, which caused a scrollbar to appear. Confirmed that without specifying width, the search bar is still full width, and no horizontal scrollbar.

Tested with various screen sizes and on Chrome/Firefox. Also confirmed that other instances of `d2l-input-search` generally don't specify a width - some do specify a max-width, but that appears to be for design purposes (e.g. the search is in a larger container, rather than the already-constrained dropdown content).

Before/after below. I also validated that this doesn't have issues with resizing when the dropdown expands or shrinks.

Before:

https://github.com/user-attachments/assets/e91a9597-891d-48b3-965d-1a72ebbbca6f

After:

https://github.com/user-attachments/assets/b4c54244-75a6-4e56-ac68-f214c1aa57f5

### CODE REVIEW

**Comment by ryantmer** [comment]
@johngwilkinson I do note that this was specifically added in https://github.com/Brightspace/insights-engagement-dashboard/commit/54bfd1c17d89436e2f7013519cd58cf5a6154b23. I suspect that `d2l-dropdown` itself has probably removed the need for this at some point in the past four years, but if there's a particular issue you can remember that this addressed, I'll make sure to check that too.

**Comment by johngwilkinson** [comment]
Interesting that the scroll bar doesn't appear in the vdiff either before or after --- @ryantmer out of interest, what browser and OS are you using?

Git blame says that line was added by @Vitalii-Misechko, but I think that was just as part of moving the repo.

The diff looks okay. I have no idea if there might be another scenario (e.g. different viewport size) where this would be an issue.

**Comment by ryantmer** [comment]
> Interesting that the scroll bar doesn't appear in the vdiff either before or after --- @ryantmer out of interest, what browser and OS are you using?
> 
> Git blame says that line was added by @Vitalii-Misechko, but I think that was just as part of moving the repo.
> 
> The diff looks okay. I have no idea if there might be another scenario (e.g. different viewport size) where this would be an issue.

I'm on Windows, and see it in both Chrome and Firefox, and am seeing it in all screen sizes too. Not mobile view I suppose, but I don't think the dashboard pages have specific mobile views, not that I could get to trigger at least. I was also surprised about no scrollbar in the "before" vdiff, although the change (a slightly less wide search bar) is what I would expect.

But yeah, had to dig a bit to find where it came from 😅 Definitely not trying to throw you under the bus haha, just making sure there wasn't a vague memory of some specific circumstance where this is important that I missed!

**Comment by johngwilkinson** [comment]
> @johngwilkinson I do note that this was specifically added in https://github.com/Brightspace/insights-engagement-dashboard/commit/54bfd1c17d89436e2f7013519cd58cf5a6154b23.

Oh, by me! 😮 

Well, I don't remember why I had that specific bit, but if you cover what I did in the testing notes there, you should be fine. Particularly different browsers and arabic I would think: 

- browsers: chrome, ff, edgacy, edgium
- expand/collapse, check & uncheck - all as expected
- rtl: confirmed indentation and padding is as expected, and layout is reversed (tested on demo page and in LMS with arabic user locale)

**Comment by johngwilkinson** [comment]
> * browsers: chrome, ff, edgacy, edgium

(edgacy being the version of MS Edge before they switched to a chromium-based code line --- I don't suppose we still support that, but I don't know)

**Comment by ryantmer** [comment]
Right, Edge exists 😆 Actually a good thing you mentioned it, since it shows there, so I suspect this is a Chromium thing. Not sure I'd call it a bug, since the content is indeed wider than the container with that `width` specified, so if anything maybe Firefox isn't showing a scrollbar when it should. (Also we recently dropped support for old Edge, hooray!)

Good note about RTL though, I did forget that - just checked it too though, and looks the same (no scroll bar or other weirdness) there. To be ultra-safe, I also won't backport this change to 24.08 (#68 will once it's merged).

**Comment by ryantmer** [comment]
vdiff failure there appears to be unrelated - I was seeing that on the main branch as well, and "fixed" it in https://github.com/BrightspaceUILabs/ou-filter/pull/68. Unfortunately it's one of those unpleasant rendering-timing flakes.

**Review by johngwilkinson — APPROVED** [review]

**Pull request merged**
